language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lakshyapurwar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lakshyapurwar/react-test npm test

after_success:
  - docker build -t lakshyapurwar/multi-client ./client
  - docker build -t lakshyapurwar/multi-nginx ./nginx
  - docker build -t lakshyapurwar/multi-server ./server
  - docker build -t lakshyapurwar/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lakshyapurwar/multi-client
  - docker push lakshyapurwar/multi-nginx
  - docker push lakshyapurwar/multi-server
  - docker push lakshyapurwar/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-162239014893"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  version_label: $TRAVIS_BUILD_NUMBER
